name: the_market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Helpers
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity: ^3.0.6
  pretty_dio_logger: ^1.1.1
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11

  #Widgets
  flutter_rating_bar: ^4.0.1
  
  # Http
  dio: ^4.0.6

  # Architecture
  redux: ^5.0.0
  rxdart: ^0.27.5
  redux_epics: ^0.15.1
  flutter_redux: ^0.10.0
  auto_route: ^4.2.1

  # Widgets
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  json_serializable: ^6.3.1
  retrofit_generator: 4.0.3+1
  build_runner: ^2.2.0
  auto_route_generator: ^4.2.1
  freezed: ^2.1.0+1

  flutter_launcher_icons: ^0.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/black_cart.png
    - assets/png/white_cart.png
    - assets/png/question_mark.png


    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
